name: Release Lib

on: 
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Integration tests
        uses: actions/setup-node@v1        
        with:
            node-version: '12'
      
      - run: npm install
      - run: npm run lint
      - run: npm run test
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      
      - run: npm run build
      - run: npm publish
