name: "[PR] Run Tests"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Integration tests
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      - run: yarn
      - run: yarn lint
      - run: yarn test
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
