name: test

on:
  pull_request:
  push:
    branches:
        - master

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Integration tests
        uses: actions/setup-node@v1        
        with:
            node-version: '12'
      - run: npm run test
        env:
            CLIENT_ID: ${{ secrets.CLIENT_ID }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}