name: "[PR] Verify App Version"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  get-current-version:
    name: Get Current Version
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' }}
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v1

      - id: get_version
        name: Get version
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"

  get-master-version:
    name: Get Master Version
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' }}
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v1
        with:
          ref: master

      - id: get_version
        name: Get version
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}" 

  verify:
    name: Verify versions
    if: ${{ github.base_ref == 'master' }}
    needs: [get-current-version, get-master-version]
    runs-on: ubuntu-latest
    steps:
      - id: verify_versions
        name: Verify versions
        shell: bash
        run: |
          verlte() {
            [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
          }

          verlt() {
            [ "$1" = "$2" ] && return 1 || verlte $1 $2
          }

          if verlt  ${{ needs.get-master-version.outputs.version }} ]] ${{ needs.get-current-version.outputs.version }}  ; then
            echo 'Version is ok!'
          else
            echo 'Must bump app version' && exit 1
          fi
        
        